//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDemotivator
{
    using System;
    using System.Collections.Generic;
    
    public partial class rate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rate()
        {
            this.IsRate = false;
        }
    
        public int Id { get; set; }
        public int DemotivatorId { get; set; }
        public string AspNetUserId { get; set; }
        public Nullable<int> Count { get; set; }
        public bool IsRate { get; set; }
    
        public virtual Demotivator Demotivator { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
