//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDemotivator.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IDemotivator.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 173434464182424.
        /// </summary>
        public static string CloudinaryApi {
            get {
                return ResourceManager.GetString("CloudinaryApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aniknaemm.
        /// </summary>
        public static string CloudinaryCloud {
            get {
                return ResourceManager.GetString("CloudinaryCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p3LleRLwWAxpm9yU3CHT63qKp_E.
        /// </summary>
        public static string CloudinarySecret {
            get {
                return ResourceManager.GetString("CloudinarySecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my_index_site.
        /// </summary>
        public static string ElasticNestSite {
            get {
                return ResourceManager.GetString("ElasticNestSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://IlwEAOgvDkuHk3yiB74RhwSs1YC0KCUu:@aniknaemm.east-us.azr.facetflow.io.
        /// </summary>
        public static string ElasticNestUri {
            get {
                return ResourceManager.GetString("ElasticNestUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demotivatorme@gmail.com.
        /// </summary>
        public static string GmailLogin {
            get {
                return ResourceManager.GetString("GmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itransition99a.
        /// </summary>
        public static string GmailPassword {
            get {
                return ResourceManager.GetString("GmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        public static string GmailSmtp {
            get {
                return ResourceManager.GetString("GmailSmtp", resourceCulture);
            }
        }
    }
}
